import { useState, useCallback, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { api } from '@/services/api';
import { TopBar, PageHeader } from '@/components/TopBar';
import { Card, CardHeader, Stat, Pill, Button } from '@/components/ui';
import { fmtDateTime } from '@/utils/format';
import type { ReviewerDashboard as ReviewerDashType } from '@/types';
import { Sparkles, ListChecks, Clock, ArrowRight, AlertOctagon } from 'lucide-react';

export function ReviewerDashboard() {
  const nav = useNavigate();
  const [data, setData] = useState<ReviewerDashType | null>(null);
  const [loading, setLoading] = useState(true);

  const load = useCallback(async () => {
    setLoading(true);
    try {
      setData(await api.getReviewerDashboard());
    } catch {
      setData(null);
    }
    setLoading(false);
  }, []);

  useEffect(() => {
    load();
  }, [load]);

  if (loading && !data) {
    return (
      <div>
        <TopBar breadcrumb={<span>Reviewer</span>} />
        <PageHeader title="Reviewer dashboard" subtitle="Loading…" />
      </div>
    );
  }

  const d = data ?? {
    by_severity: { high: 0, medium: 0, low: 0 },
    pending_decisions: 0,
    recent_decisions: [],
    ai_summary: 'No open exceptions in database queue.',
  };

  return (
    <div>
      <TopBar
        breadcrumb={
          <>
            <span>Reviewer</span>
            <span className="text-warmink-mute/50">/</span>
            <span className="text-warmink">Dashboard</span>
          </>
        }
      />
      <PageHeader
        title="Reviewer dashboard"
        subtitle="Triage the exception queue, consult the AI assistant, and make the final call on every flagged record."
        right={
          <Button variant="primary" onClick={() => nav('/reviewer/queue')}>
            <ListChecks className="w-4 h-4" strokeWidth={1.75} />
            Open exception queue
          </Button>
        }
      />

      <div className="px-6 lg:px-10 py-8 space-y-8">
        <div className="grid grid-cols-2 md:grid-cols-4 gap-px bg-warmink/12 border border-warmink/12">
          <Stat label="Pending decisions" value={d.pending_decisions} tone="pending" />
          <Stat label="High severity" value={d.by_severity.high} tone="exception" />
          <Stat label="Medium severity" value={d.by_severity.medium} tone="pending" />
          <Stat label="Low severity" value={d.by_severity.low} />
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          <Card surface="ink" className="lg:col-span-2">
            <CardHeader
              title="AI queue summary"
              subtitle="The assistant's plain-English read of current queue exceptions"
              right={<Sparkles className="w-4 h-4 text-verified-light" strokeWidth={1.75} />}
            />
            <div className="p-5">
              <p className="text-sm text-paper/90 leading-relaxed max-w-ledger">
                {d.ai_summary}
              </p>
              <p className="mt-4 text-2xs text-paper/40 font-mono uppercase tracking-wide">
                Generated by gemini-2.5-flash · tabular figures and pattern detection
              </p>
            </div>
          </Card>

          <Card>
            <CardHeader
              title="Pending decisions"
              subtitle="Open exceptions awaiting your sign-off"
              right={<Clock className="w-4 h-4 text-pending-dark" strokeWidth={1.75} />}
            />
            <div className="p-5">
              <p className="font-slab text-3xl text-warmink tnum font-semibold">
                {d.pending_decisions}
              </p>
              <p className="text-xs text-warmink-mute mt-1">
                open exceptions requiring human decision
              </p>
              <Button
                variant="secondary"
                className="mt-5 w-full"
                onClick={() => nav('/reviewer/queue')}
              >
                Work the queue
                <ArrowRight className="w-3.5 h-3.5" strokeWidth={1.75} />
              </Button>
            </div>
          </Card>
        </div>

        <Card>
          <CardHeader
            title="Recent decisions"
            subtitle="The last calls made on flagged records by reviewers"
          />
          {d.recent_decisions.length === 0 ? (
            <div className="p-5 text-sm text-warmink-mute flex items-center gap-2">
              <AlertOctagon className="w-4 h-4" strokeWidth={1.75} />
              No decisions yet — open the exception queue to start reviewing.
            </div>
          ) : (
            <ul className="divide-y divide-warmink/10">
              {d.recent_decisions.map((dec, i) => (
                <li key={i} className="flex items-center justify-between gap-4 px-5 py-3.5">
                  <button
                    onClick={() => nav(`/reviewer/loan/${dec.loan_id}`)}
                    className="font-mono text-sm text-warmink hover:underline font-medium"
                  >
                    {dec.loan_id}
                  </button>
                  <div className="flex items-center gap-3">
                    <Pill
                      tone={
                        dec.decision === 'approved'
                          ? 'verified'
                          : dec.decision === 'rejected'
                            ? 'exception'
                            : 'pending'
                      }
                    >
                      {dec.decision.replace(/_/g, ' ')}
                    </Pill>
                    <span className="text-xs text-warmink-mute hidden sm:inline">{dec.actor}</span>
                    <span className="font-mono text-2xs text-warmink-mute">
                      {fmtDateTime(dec.at)}
                    </span>
                  </div>
                </li>
              ))}
            </ul>
          )}
        </Card>
      </div>
    </div>
  );
}
