import { useState, useCallback, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { api } from '@/services/api';
import { TopBar, PageHeader } from '@/components/TopBar';
import { Card, CardHeader, Stat, Pill, Button } from '@/components/ui';
import { fmtDateTime } from '@/utils/format';
import type { ReviewerDashboard as ReviewerDashType } from '@/types';
import { Sparkles, ListChecks, Clock, ArrowRight, AlertOctagon, PlusCircle, CheckCircle2, XCircle } from 'lucide-react';

export function ReviewerDashboard() {
  const nav = useNavigate();
  const [data, setData] = useState<ReviewerDashType | null>(null);
  const [loading, setLoading] = useState(true);

  // AI Rule Generation State
  const [rulePrompt, setRulePrompt] = useState('');
  const [generatingRule, setGeneratingRule] = useState(false);
  const [ruleDraft, setRuleDraft] = useState<any | null>(null);
  const [ruleMsg, setRuleMsg] = useState<string | null>(null);

  const load = useCallback(async () => {
    setLoading(true);
    try {
      setData(await api.getReviewerDashboard());
    } catch {
      setData(null);
    }
    setLoading(false);
  }, []);

  useEffect(() => {
    load();
  }, [load]);

  const handleGenerateRule = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!rulePrompt.trim()) return;
    setGeneratingRule(true);
    setRuleMsg(null);
    try {
      const res: any = await api.requestAIRuleGeneration(rulePrompt.trim());
      setRuleDraft(res.rule || res);
      setRuleMsg('AI generated new rule logic! Review and approve below.');
    } catch (err: any) {
      setRuleMsg(`Error generating rule: ${err?.message || 'AI request failed'}`);
    } finally {
      setGeneratingRule(false);
    }
  };

  const handleApproveRule = async (ruleId: string) => {
    try {
      await api.approveAIRuleDraft(ruleId);
      setRuleMsg('Rule approved & activated in engine!');
      setRuleDraft(null);
      setRulePrompt('');
    } catch (err: any) {
      setRuleMsg(`Error approving rule: ${err?.message}`);
    }
  };

  const handleRejectRule = async (ruleId: string) => {
    try {
      await api.rejectAIRuleDraft(ruleId);
      setRuleMsg('Rule proposal rejected.');
      setRuleDraft(null);
    } catch (err: any) {
      setRuleMsg(`Error rejecting rule: ${err?.message}`);
    }
  };

  if (loading && !data) {
    return (
      <div>
        <TopBar breadcrumb={<span>Reviewer</span>} />
        <PageHeader title="Reviewer dashboard" subtitle="Loading…" />
      </div>
    );
  }

  const d = data ?? {
    by_severity: { high: 0, medium: 0, low: 0 },
    pending_decisions: 0,
    recent_decisions: [],
    ai_summary: 'No open exceptions in database queue.',
  };

  return (
    <div>
      <TopBar
        breadcrumb={
          <>
            <span>Reviewer</span>
            <span className="text-warmink-mute/50">/</span>
            <span className="text-warmink">Dashboard</span>
          </>
        }
      />
      <PageHeader
        title="Reviewer dashboard"
        subtitle="Triage the exception queue, consult the AI assistant, and make the final call on every flagged record."
        right={
          <Button variant="primary" onClick={() => nav('/reviewer/queue')}>
            <ListChecks className="w-4 h-4" strokeWidth={1.75} />
            Open exception queue
          </Button>
        }
      />

      <div className="px-6 lg:px-10 py-8 space-y-8">
        <div className="grid grid-cols-2 md:grid-cols-4 gap-px bg-warmink/12 border border-warmink/12">
          <Stat label="Pending decisions" value={d.pending_decisions} tone="pending" />
          <Stat label="High severity" value={d.by_severity.high} tone="exception" />
          <Stat label="Medium severity" value={d.by_severity.medium} tone="pending" />
          <Stat label="Low severity" value={d.by_severity.low} />
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          <Card surface="ink" className="lg:col-span-2">
            <CardHeader
              title="AI queue summary"
              subtitle="The assistant's plain-English read of current queue exceptions"
              right={<Sparkles className="w-4 h-4 text-verified-light" strokeWidth={1.75} />}
            />
            <div className="p-5">
              <p className="text-sm text-paper/90 leading-relaxed max-w-ledger">
                {d.ai_summary}
              </p>
              <p className="mt-4 text-2xs text-paper/40 font-mono uppercase tracking-wide">
                Generated by gemini-2.5-flash · tabular figures and pattern detection
              </p>
            </div>
          </Card>

          <Card>
            <CardHeader
              title="Pending decisions"
              subtitle="Open exceptions awaiting your sign-off"
              right={<Clock className="w-4 h-4 text-pending-dark" strokeWidth={1.75} />}
            />
            <div className="p-5">
              <p className="font-slab text-3xl text-warmink tnum font-semibold">
                {d.pending_decisions}
              </p>
              <p className="text-xs text-warmink-mute mt-1">
                open exceptions requiring human decision
              </p>
              <Button
                variant="secondary"
                className="mt-5 w-full"
                onClick={() => nav('/reviewer/queue')}
              >
                Work the queue
                <ArrowRight className="w-3.5 h-3.5" strokeWidth={1.75} />
              </Button>
            </div>
          </Card>
        </div>

        {/* AI Rule Creation & Proposal Section */}
        <Card>
          <CardHeader
            title="AI Natural Language Rule Generator"
            subtitle="Describe a custom validation logic in natural language — Gemini will generate the JSON rule configuration."
            right={<Sparkles className="w-4 h-4 text-amber-600" strokeWidth={1.75} />}
          />
          <div className="p-5">
            <form onSubmit={handleGenerateRule} className="flex flex-col sm:flex-row gap-3">
              <input
                type="text"
                value={rulePrompt}
                onChange={(e) => setRulePrompt(e.target.value)}
                placeholder="e.g. Flag any loan where interest rate exceeds 12% or original principal is above 2M"
                className="flex-1 px-3.5 py-2 text-sm bg-parchment-light border border-warmink/20 focus:border-ink/40 outline-none font-sans"
              />
              <Button variant="primary" type="submit" disabled={generatingRule}>
                <PlusCircle className="w-4 h-4" />
                {generatingRule ? 'Generating Rule…' : 'Generate Rule'}
              </Button>
            </form>

            {ruleMsg && (
              <p className="mt-3 text-xs text-warmink font-mono bg-parchment p-2 border border-warmink/15">
                {ruleMsg}
              </p>
            )}

            {ruleDraft && (
              <div className="mt-4 p-4 bg-parchment-lighter border border-warmink/20 space-y-3">
                <div className="flex items-center justify-between">
                  <div>
                    <span className="font-mono text-xs text-warmink font-bold">{ruleDraft.code || 'CUSTOM_RULE'}</span>
                    <span className="ml-2 text-xs text-warmink-soft font-medium">{ruleDraft.name}</span>
                  </div>
                  <Pill tone="pending">{ruleDraft.severity || 'medium'}</Pill>
                </div>
                <pre className="text-2xs font-mono bg-paper p-3 border border-warmink/15 overflow-x-auto text-warmink">
                  {JSON.stringify(ruleDraft.config || ruleDraft, null, 2)}
                </pre>
                <div className="flex gap-2">
                  <Button variant="verified" onClick={() => handleApproveRule(ruleDraft.id)}>
                    <CheckCircle2 className="w-3.5 h-3.5" /> Approve & Activate Rule
                  </Button>
                  <Button variant="danger" onClick={() => handleRejectRule(ruleDraft.id)}>
                    <XCircle className="w-3.5 h-3.5" /> Reject Proposal
                  </Button>
                </div>
              </div>
            )}
          </div>
        </Card>

        <Card>
          <CardHeader
            title="Recent decisions"
            subtitle="The last calls made on flagged records by reviewers"
          />
          {d.recent_decisions.length === 0 ? (
            <div className="p-5 text-sm text-warmink-mute flex items-center gap-2">
              <AlertOctagon className="w-4 h-4" strokeWidth={1.75} />
              No decisions yet — open the exception queue to start reviewing.
            </div>
          ) : (
            <ul className="divide-y divide-warmink/10">
              {d.recent_decisions.map((dec, i) => (
                <li key={i} className="flex items-center justify-between gap-4 px-5 py-3.5">
                  <button
                    onClick={() => nav(`/reviewer/loan/${dec.loan_id}`)}
                    className="font-mono text-sm text-warmink hover:underline font-medium"
                  >
                    {dec.loan_id}
                  </button>
                  <div className="flex items-center gap-3">
                    <Pill
                      tone={
                        dec.decision === 'approved'
                          ? 'verified'
                          : dec.decision === 'rejected'
                            ? 'exception'
                            : 'pending'
                      }
                    >
                      {dec.decision.replace(/_/g, ' ')}
                    </Pill>
                    <span className="text-xs text-warmink-mute hidden sm:inline">{dec.actor}</span>
                    <span className="font-mono text-2xs text-warmink-mute">
                      {fmtDateTime(dec.at)}
                    </span>
                  </div>
                </li>
              ))}
            </ul>
          )}
        </Card>
      </div>
    </div>
  );
}
