import type {
  LoanRecord,
  Exception,
  AIRecommendation,
  VerifiedRecord,
  AuditEvent,
  ImportEvent,
  OperatorDashboard,
  ReviewerDashboard,
  ConsumerDashboard,
  Summary,
} from './types';

const t = (d: string, h = '09:14:00') => `${d}T${h}Z`;

export const loans: LoanRecord[] = [
  {
    loan_id: 'LN-100201',
    borrower_id: 'BR-58213',
    loan_type: 'Conventional',
    origination_date: '2023-02-14',
    maturity_date: '2053-02-14',
    original_principal: 412000,
    current_balance: 398120.55,
    interest_rate: 6.125,
    term_months: 360,
    borrower_state: 'CA',
    payment_status: 'Current',
    days_past_due: 0,
    servicer_name: 'Cascade Servicing',
    document_status: 'Complete',
    source_system: 'Encompass',
  },
  {
    loan_id: 'LN-100202',
    borrower_id: 'BR-58214',
    loan_type: 'FHA',
    origination_date: '2023-04-02',
    maturity_date: '2053-04-02',
    original_principal: 286500,
    current_balance: 279440.1,
    interest_rate: 5.75,
    term_months: 360,
    borrower_state: 'TX',
    payment_status: '30 DPD',
    days_past_due: 31,
    servicer_name: 'Heartland Mortgage',
    document_status: 'Complete',
    source_system: 'Byte',
  },
  {
    loan_id: 'LN-100203',
    borrower_id: 'BR-58215',
    loan_type: 'VA',
    origination_date: '2023-05-21',
    maturity_date: '2053-05-21',
    original_principal: 355000,
    current_balance: 341220.0,
    interest_rate: 5.5,
    term_months: 360,
    borrower_state: 'FL',
    payment_status: 'Current',
    days_past_due: 0,
    servicer_name: 'Cascade Servicing',
    document_status: 'Pending Review',
    source_system: 'Calyx Point',
  },
  {
    loan_id: 'LN-100204',
    borrower_id: 'BR-58216',
    loan_type: 'Jumbo',
    origination_date: '2023-06-18',
    maturity_date: '2043-06-18',
    original_principal: 905000,
    current_balance: 902100.0,
    interest_rate: 6.625,
    term_months: 240,
    borrower_state: 'NY',
    payment_status: 'Current',
    days_past_due: 0,
    servicer_name: 'Summit Capital',
    document_status: 'Complete',
    source_system: 'Encompass',
  },
  {
    loan_id: 'LN-100205',
    borrower_id: 'BR-58217',
    loan_type: 'Conventional',
    origination_date: '2023-07-09',
    maturity_date: '2043-07-09',
    original_principal: 268000,
    current_balance: 265300.0,
    interest_rate: 6.0,
    term_months: 240,
    borrower_state: 'AZ',
    payment_status: '60 DPD',
    days_past_due: 62,
    servicer_name: 'Heartland Mortgage',
    document_status: 'Complete',
    source_system: 'MortgageCadence',
  },
  {
    loan_id: 'LN-100206',
    borrower_id: 'BR-58218',
    loan_type: 'HELOC',
    origination_date: '2023-09-01',
    maturity_date: '2043-09-01',
    original_principal: 145000,
    current_balance: 142880.0,
    interest_rate: 7.25,
    term_months: 240,
    borrower_state: 'WA',
    payment_status: 'Current',
    days_past_due: 0,
    servicer_name: 'Summit Capital',
    document_status: 'Missing',
    source_system: 'LendingQB',
  },
  {
    loan_id: 'LN-100207',
    borrower_id: 'BR-58219',
    loan_type: 'USDA',
    origination_date: '2023-10-12',
    maturity_date: '2053-10-12',
    original_principal: 198500,
    current_balance: 194220.0,
    interest_rate: 5.375,
    term_months: 360,
    borrower_state: 'OR',
    payment_status: 'Current',
    days_past_due: 0,
    servicer_name: 'Cascade Servicing',
    document_status: 'Complete',
    source_system: 'Byte',
  },
  {
    loan_id: 'LN-100208',
    borrower_id: 'BR-58220',
    loan_type: 'Conventional',
    origination_date: '2023-11-23',
    maturity_date: '2053-11-23',
    original_principal: 524000,
    current_balance: 521400.0,
    interest_rate: 6.25,
    term_months: 360,
    borrower_state: 'CO',
    payment_status: '90+ DPD',
    days_past_due: 96,
    servicer_name: 'Heartland Mortgage',
    document_status: 'Complete',
    source_system: 'Encompass',
  },
  {
    loan_id: 'LN-100209',
    borrower_id: 'BR-58221',
    loan_type: 'FHA',
    origination_date: '2024-01-05',
    maturity_date: '2054-01-05',
    original_principal: 312000,
    current_balance: 309800.0,
    interest_rate: 6.0,
    term_months: 360,
    borrower_state: 'GA',
    payment_status: 'Current',
    days_past_due: 0,
    servicer_name: 'Summit Capital',
    document_status: 'Complete',
    source_system: 'Calyx Point',
  },
  {
    loan_id: 'LN-100210',
    borrower_id: 'BR-58222',
    loan_type: 'VA',
    origination_date: '2024-02-19',
    maturity_date: '2054-02-19',
    original_principal: 401000,
    current_balance: 398900.0,
    interest_rate: 5.875,
    term_months: 360,
    borrower_state: 'NC',
    payment_status: 'Current',
    days_past_due: 0,
    servicer_name: 'Cascade Servicing',
    document_status: 'Pending Review',
    source_system: 'MortgageCadence',
  },
  {
    loan_id: 'LN-100211',
    borrower_id: 'BR-58223',
    loan_type: 'Jumbo',
    origination_date: '2024-03-30',
    maturity_date: '2044-03-30',
    original_principal: 1120000,
    current_balance: 1118200.0,
    interest_rate: 6.5,
    term_months: 240,
    borrower_state: 'CA',
    payment_status: 'Current',
    days_past_due: 0,
    servicer_name: 'Summit Capital',
    document_status: 'Complete',
    source_system: 'Encompass',
  },
  {
    loan_id: 'LN-100212',
    borrower_id: 'BR-58224',
    loan_type: 'Conventional',
    origination_date: '2024-04-11',
    maturity_date: '2054-04-11',
    original_principal: 342000,
    current_balance: 339600.0,
    interest_rate: 6.375,
    term_months: 360,
    borrower_state: 'TX',
    payment_status: '30 DPD',
    days_past_due: 28,
    servicer_name: 'Heartland Mortgage',
    document_status: 'Complete',
    source_system: 'Byte',
  },
  {
    loan_id: 'LN-100213',
    borrower_id: 'BR-58225',
    loan_type: 'HELOC',
    origination_date: '2024-05-22',
    maturity_date: '2044-05-22',
    original_principal: 98000,
    current_balance: 96400.0,
    interest_rate: 7.5,
    term_months: 240,
    borrower_state: 'MI',
    payment_status: 'Current',
    days_past_due: 0,
    servicer_name: 'Cascade Servicing',
    document_status: 'Complete',
    source_system: 'LendingQB',
  },
  {
    loan_id: 'LN-100214',
    borrower_id: 'BR-58226',
    loan_type: 'FHA',
    origination_date: '2024-06-14',
    maturity_date: '2054-06-14',
    original_principal: 224500,
    current_balance: 222800.0,
    interest_rate: 6.125,
    term_months: 360,
    borrower_state: 'OH',
    payment_status: 'Current',
    days_past_due: 0,
    servicer_name: 'Summit Capital',
    document_status: 'Missing',
    source_system: 'Calyx Point',
  },
  {
    loan_id: 'LN-100215',
    borrower_id: 'BR-58227',
    loan_type: 'Conventional',
    origination_date: '2024-07-02',
    maturity_date: '2044-07-02',
    original_principal: 478000,
    current_balance: 475200.0,
    interest_rate: 6.25,
    term_months: 240,
    borrower_state: 'IL',
    payment_status: 'Current',
    days_past_due: 0,
    servicer_name: 'Heartland Mortgage',
    document_status: 'Complete',
    source_system: 'Encompass',
  },
  {
    loan_id: 'LN-100216',
    borrower_id: 'BR-58228',
    loan_type: 'USDA',
    origination_date: '2024-08-19',
    maturity_date: '2054-08-19',
    original_principal: 176000,
    current_balance: 174100.0,
    interest_rate: 5.5,
    term_months: 360,
    borrower_state: 'IA',
    payment_status: 'Current',
    days_past_due: 0,
    servicer_name: 'Cascade Servicing',
    document_status: 'Complete',
    source_system: 'MortgageCadence',
  },
  {
    loan_id: 'LN-100217',
    borrower_id: 'BR-58229',
    loan_type: 'Jumbo',
    origination_date: '2024-09-05',
    maturity_date: '2049-09-05',
    original_principal: 845000,
    current_balance: 842000.0,
    interest_rate: 6.75,
    term_months: 300,
    borrower_state: 'NJ',
    payment_status: 'Current',
    days_past_due: 0,
    servicer_name: 'Summit Capital',
    document_status: 'Complete',
    source_system: 'Encompass',
  },
  {
    loan_id: 'LN-100218',
    borrower_id: 'BR-58230',
    loan_type: 'Conventional',
    origination_date: '2024-10-11',
    maturity_date: '2054-10-11',
    original_principal: 389000,
    current_balance: 386400.0,
    interest_rate: 6.375,
    term_months: 360,
    borrower_state: 'PA',
    payment_status: '60 DPD',
    days_past_due: 58,
    servicer_name: 'Heartland Mortgage',
    document_status: 'Complete',
    source_system: 'Byte',
  },
  {
    loan_id: 'LN-100219',
    borrower_id: 'BR-58231',
    loan_type: 'VA',
    origination_date: '2024-11-27',
    maturity_date: '2054-11-27',
    original_principal: 298000,
    current_balance: 295900.0,
    interest_rate: 5.75,
    term_months: 360,
    borrower_state: 'VA',
    payment_status: 'Current',
    days_past_due: 0,
    servicer_name: 'Cascade Servicing',
    document_status: 'Pending Review',
    source_system: 'Calyx Point',
  },
  {
    loan_id: 'LN-100220',
    borrower_id: 'BR-58232',
    loan_type: 'FHA',
    origination_date: '2025-01-08',
    maturity_date: '2055-01-08',
    original_principal: 256000,
    current_balance: 253800.0,
    interest_rate: 6.0,
    term_months: 360,
    borrower_state: 'NV',
    payment_status: 'Current',
    days_past_due: 0,
    servicer_name: 'Summit Capital',
    document_status: 'Complete',
    source_system: 'MortgageCadence',
  },
  {
    loan_id: 'LN-100221',
    borrower_id: 'BR-58233',
    loan_type: 'Conventional',
    origination_date: '2025-02-15',
    maturity_date: '2055-02-15',
    original_principal: 467000,
    current_balance: 464900.0,
    interest_rate: 6.25,
    term_months: 360,
    borrower_state: 'MN',
    payment_status: 'Current',
    days_past_due: 0,
    servicer_name: 'Heartland Mortgage',
    document_status: 'Complete',
    source_system: 'Encompass',
  },
  {
    loan_id: 'LN-100222',
    borrower_id: 'BR-58234',
    loan_type: 'HELOC',
    origination_date: '2025-03-21',
    maturity_date: '2045-03-21',
    original_principal: 165000,
    current_balance: 163200.0,
    interest_rate: 7.375,
    term_months: 240,
    borrower_state: 'MA',
    payment_status: 'Current',
    days_past_due: 0,
    servicer_name: 'Cascade Servicing',
    document_status: 'Missing',
    source_system: 'LendingQB',
  },
  {
    loan_id: 'LN-100223',
    borrower_id: 'BR-58235',
    loan_type: 'Jumbo',
    origination_date: '2025-04-09',
    maturity_date: '2055-04-09',
    original_principal: 980000,
    current_balance: 977600.0,
    interest_rate: 6.5,
    term_months: 360,
    borrower_state: 'CT',
    payment_status: 'Current',
    days_past_due: 0,
    servicer_name: 'Summit Capital',
    document_status: 'Complete',
    source_system: 'Encompass',
  },
  {
    loan_id: 'LN-100224',
    borrower_id: 'BR-58236',
    loan_type: 'Conventional',
    origination_date: '2025-05-23',
    maturity_date: '2055-05-23',
    original_principal: 351000,
    current_balance: 348900.0,
    interest_rate: 6.375,
    term_months: 360,
    borrower_state: 'UT',
    payment_status: '30 DPD',
    days_past_due: 24,
    servicer_name: 'Heartland Mortgage',
    document_status: 'Complete',
    source_system: 'Byte',
  },
];

export const exceptions: Exception[] = [
  {
    id: 'EX-5001',
    loan_id: 'LN-100203',
    rule_type: 'document_complete',
    severity: 'low',
    status: 'open',
    detected_at: t('2026-08-18', '10:02:11'),
    field: 'document_status',
    detail: 'Document status is "Pending Review" — title binder not on file.',
  },
  {
    id: 'EX-5002',
    loan_id: 'LN-100206',
    rule_type: 'document_complete',
    severity: 'high',
    status: 'open',
    detected_at: t('2026-08-18', '10:02:11'),
    field: 'document_status',
    detail: 'Document status is "Missing" — no closing disclosure or note attached.',
  },
  {
    id: 'EX-5003',
    loan_id: 'LN-100208',
    rule_type: 'dpd_status_match',
    severity: 'high',
    status: 'open',
    detected_at: t('2026-08-18', '10:02:12'),
    field: 'days_past_due',
    detail: 'Days past due (96) exceeds the 90+ DPD threshold; payment_status shows "90+ DPD" but no default flag is set on the servicer record.',
  },
  {
    id: 'EX-5004',
    loan_id: 'LN-100210',
    rule_type: 'document_complete',
    severity: 'low',
    status: 'open',
    detected_at: t('2026-08-18', '10:02:13'),
    field: 'document_status',
    detail: 'Document status is "Pending Review" — appraisal addendum pending.',
  },
  {
    id: 'EX-5005',
    loan_id: 'LN-100214',
    rule_type: 'document_complete',
    severity: 'high',
    status: 'open',
    detected_at: t('2026-08-19', '09:30:40'),
    field: 'document_status',
    detail: 'Document status is "Missing" — loan estimate and closing disclosure both absent.',
  },
  {
    id: 'EX-5006',
    loan_id: 'LN-100219',
    rule_type: 'document_complete',
    severity: 'low',
    status: 'open',
    detected_at: t('2026-08-19', '09:30:42'),
    field: 'document_status',
    detail: 'Document status is "Pending Review" — VA funding fee receipt pending upload.',
  },
  {
    id: 'EX-5007',
    loan_id: 'LN-100222',
    rule_type: 'document_complete',
    severity: 'high',
    status: 'open',
    detected_at: t('2026-08-20', '11:14:05'),
    field: 'document_status',
    detail: 'Document status is "Missing" — HELOC agreement not attached.',
  },
  {
    id: 'EX-5008',
    loan_id: 'LN-100224',
    rule_type: 'dpd_status_match',
    severity: 'medium',
    status: 'open',
    detected_at: t('2026-08-20', '11:14:07'),
    field: 'days_past_due',
    detail: 'Days past due (24) is below the 30 DPD threshold but payment_status is "30 DPD". Status may be premature.',
  },
  {
    id: 'EX-5009',
    loan_id: 'LN-100205',
    rule_type: 'dpd_status_match',
    severity: 'medium',
    status: 'correction_requested',
    detected_at: t('2026-08-17', '14:22:18'),
    field: 'days_past_due',
    detail: 'Days past due (62) sits in the 60 DPD band but payment_status shows "60 DPD" — confirm with servicer before verifying.',
  },
  {
    id: 'EX-5010',
    loan_id: 'LN-100201',
    rule_type: 'balance_under_principal',
    severity: 'low',
    status: 'approved',
    detected_at: t('2026-08-16', '08:40:00'),
    field: 'current_balance',
    detail: 'Reviewed and approved — balance amortization within tolerance.',
  },
];

export const recommendations: AIRecommendation[] = [
  {
    id: 'AI-7001',
    exception_id: 'EX-5001',
    prompt: 'Explain why LN-100203 failed document_complete and suggest a correction.',
    model: 'claude-3-5-sonnet',
    timestamp: t('2026-08-18', '10:05:00'),
    suggested_correction: 'Set document_status to "Complete" once the title binder is uploaded; request the binder from the title company.',
    explanation:
      'The loan is otherwise clean. The only failing field is document_status, which is "Pending Review" because the title binder has not been uploaded. The loan should not be verified until the binder is on file, but no data correction is needed on the loan record itself.',
    status: 'pending',
  },
  {
    id: 'AI-7002',
    exception_id: 'EX-5002',
    prompt: 'Explain why LN-100206 failed document_complete and suggest a correction.',
    model: 'claude-3-5-sonnet',
    timestamp: t('2026-08-18', '10:05:02'),
    suggested_correction:
      'Request the closing disclosure and promissory note from the originating lender before verifying. Do not change document_status manually.',
    explanation:
      'HELOC LN-100206 is missing both the closing disclosure and the note. This is a high-severity documentation gap. The record should be held for correction until the documents are supplied; the AI does not recommend marking it verified.',
    status: 'pending',
  },
  {
    id: 'AI-7003',
    exception_id: 'EX-5003',
    prompt: 'Explain why LN-100208 failed dpd_status_match and suggest a correction.',
    model: 'claude-3-5-sonnet',
    timestamp: t('2026-08-18', '10:05:05'),
    suggested_correction:
      'Confirm with Heartland Mortgage whether a default flag should be set. If so, update payment_status to "Default"; otherwise leave as-is and annotate.',
    explanation:
      'LN-100208 is 96 days past due, which crosses the 90+ DPD threshold. The payment_status field shows "90+ DPD" but the servicer record has no default flag. This is a consistency issue between the loan tape and the servicer system, not a data entry error.',
    status: 'pending',
  },
  {
    id: 'AI-7004',
    exception_id: 'EX-5004',
    prompt: 'Explain why LN-100210 failed document_complete and suggest a correction.',
    model: 'claude-3-5-sonnet',
    timestamp: t('2026-08-18', '10:05:08'),
    suggested_correction:
      'Hold for the appraisal addendum. Once uploaded, set document_status to "Complete".',
    explanation:
      'VA loan LN-100210 is otherwise consistent. The appraisal addendum is pending, which is why document_status is "Pending Review". No loan field needs correction.',
    status: 'pending',
  },
  {
    id: 'AI-7005',
    exception_id: 'EX-5005',
    prompt: 'Explain why LN-100214 failed document_complete and suggest a correction.',
    model: 'claude-3-5-sonnet',
    timestamp: t('2026-08-19', '09:33:00'),
    suggested_correction:
      'Request both the loan estimate and closing disclosure from Calyx Point export. Do not verify until both are on file.',
    explanation:
      'FHA loan LN-100214 is missing its loan estimate and closing disclosure. This is a high-severity gap. The loan should be held for correction.',
    status: 'pending',
  },
  {
    id: 'AI-7006',
    exception_id: 'EX-5006',
    prompt: 'Explain why LN-100219 failed document_complete and suggest a correction.',
    model: 'claude-3-5-sonnet',
    timestamp: t('2026-08-19', '09:33:03'),
    suggested_correction:
      'Upload the VA funding fee receipt, then set document_status to "Complete".',
    explanation:
      'VA loan LN-100219 is otherwise clean. The funding fee receipt is pending, which is the only reason document_status is "Pending Review".',
    status: 'pending',
  },
  {
    id: 'AI-7007',
    exception_id: 'EX-5007',
    prompt: 'Explain why LN-100222 failed document_complete and suggest a correction.',
    model: 'claude-3-5-sonnet',
    timestamp: t('2026-08-20', '11:16:00'),
    suggested_correction:
      'Request the HELOC agreement from LendingQB. Do not verify until attached.',
    explanation:
      'HELOC LN-100222 is missing the HELOC agreement itself — the core document for this loan type. High severity. Hold for correction.',
    status: 'pending',
  },
  {
    id: 'AI-7008',
    exception_id: 'EX-5008',
    prompt: 'Explain why LN-100224 failed dpd_status_match and suggest a correction.',
    model: 'claude-3-5-sonnet',
    timestamp: t('2026-08-20', '11:16:03'),
    suggested_correction:
      'Reconcile with Heartland Mortgage. If days_past_due is accurate at 24, set payment_status to "Current"; if 30 DPD is correct, update days_past_due to >= 30.',
    explanation:
      'LN-100224 shows 24 days past due but a payment_status of "30 DPD". These are inconsistent — 24 days should be "Current" under the standard banding. One of the two fields is wrong.',
    status: 'pending',
  },
  {
    id: 'AI-7009',
    exception_id: 'EX-5009',
    prompt: 'Explain why LN-100205 failed dpd_status_match and suggest a correction.',
    model: 'claude-3-5-sonnet',
    timestamp: t('2026-08-17', '14:25:00'),
    suggested_correction:
      'Confirm the 62 DPD figure with Heartland Mortgage. If confirmed, payment_status "60 DPD" is correct and the exception can be approved.',
    explanation:
      'LN-100205 is 62 days past due, which falls in the 60 DPD band. The payment_status field already shows "60 DPD", so the two are consistent — this exception was likely raised by a strict threshold check. A reviewer should confirm with the servicer.',
    status: 'pending',
  },
  {
    id: 'AI-7010',
    exception_id: 'EX-5010',
    prompt: 'Explain why LN-100201 raised balance_under_principal and suggest a correction.',
    model: 'claude-3-5-sonnet',
    timestamp: t('2026-08-16', '08:42:00'),
    suggested_correction: 'No correction needed. Balance is within normal amortization. Approve.',
    explanation:
      'LN-100201 has a current balance of $398,120.55 against an original principal of $412,000 — a normal reduction for a loan originated in 2023. The rule fired as a low-severity check; the record is clean.',
    status: 'accepted',
  },
];

export const verifiedRecords: VerifiedRecord[] = [
  {
    loan_id: 'LN-100201',
    canonical_data: loans[0],
    source_file_ref: 'tape_2026_08_encompass.csv',
    validation_result: 'pass',
    reviewer_decision: 'approved',
    ai_recommendation_ref: 'AI-7010',
    verified_at: t('2026-08-16', '08:51:00'),
    verified_by: 'Reviewer A',
    record_hash: '0x8a4f2c91e7b3d4a6f8c2019d3e5b7a9c4f2d1e8b6a3c5d7f9e1b4a2c8d6f3e0a',
  },
  {
    loan_id: 'LN-100202',
    canonical_data: loans[1],
    source_file_ref: 'tape_2026_08_byte.csv',
    validation_result: 'pass',
    reviewer_decision: 'approved',
    ai_recommendation_ref: null,
    verified_at: t('2026-08-15', '13:22:00'),
    verified_by: 'Reviewer B',
    record_hash: '0x3b7e9a1d4c8f2e6b0a5d3c9f1e7b4a8d2c6f0e3b5a1d7c9f4e8b2a6d0c3f1e9',
  },
  {
    loan_id: 'LN-100204',
    canonical_data: loans[3],
    source_file_ref: 'tape_2026_08_encompass.csv',
    validation_result: 'pass',
    reviewer_decision: 'approved',
    ai_recommendation_ref: null,
    verified_at: t('2026-08-14', '11:08:00'),
    verified_by: 'Reviewer A',
    record_hash: '0x5d2c8f1e7b4a9c3d6f0e2b8a5d1c7f4e9b3a6d0c2f8e1b5a7d3c9f4e0b2a6d1',
  },
  {
    loan_id: 'LN-100207',
    canonical_data: loans[6],
    source_file_ref: 'tape_2026_08_byte.csv',
    validation_result: 'pass',
    reviewer_decision: 'approved',
    ai_recommendation_ref: null,
    verified_at: t('2026-08-13', '16:40:00'),
    verified_by: 'Reviewer B',
    record_hash: '0x9f1e4b7a2d5c8f3e0b6a1d4c7f2e9b5a8d3c6f0e2b7a4d1c5f8e3b0a6d9c2f1',
  },
  {
    loan_id: 'LN-100209',
    canonical_data: loans[8],
    source_file_ref: 'tape_2026_08_calyx.csv',
    validation_result: 'pass',
    reviewer_decision: 'approved',
    ai_recommendation_ref: null,
    verified_at: t('2026-08-12', '10:15:00'),
    verified_by: 'Reviewer A',
    record_hash: '0x2b6a9d3f0e8c1f4b7a2d5c8e3b0a6d9f2e7b4a1d8c5f3e0b6a3d7c9f4e2b8a1',
  },
  {
    loan_id: 'LN-100211',
    canonical_data: loans[10],
    source_file_ref: 'tape_2026_08_encompass.csv',
    validation_result: 'pass',
    reviewer_decision: 'approved',
    ai_recommendation_ref: null,
    verified_at: t('2026-08-11', '09:50:00'),
    verified_by: 'Reviewer A',
    record_hash: '0x7c3f0e6b9d2a5c8f1e4b7a0d3c6f9e2b5a8d1c4f7e0b3a6d9c2f5e8b1a4d7c0',
  },
  {
    loan_id: 'LN-100213',
    canonical_data: loans[12],
    source_file_ref: 'tape_2026_08_lendingqb.csv',
    validation_result: 'pass',
    reviewer_decision: 'approved',
    ai_recommendation_ref: null,
    verified_at: t('2026-08-10', '14:33:00'),
    verified_by: 'Reviewer B',
    record_hash: '0x4e8b1d7c0f3a6d9c2f5e8b1a4d7c0e3b6a9d2f5c8e1b4a7d0c3f6e9b2a5d8c1',
  },
  {
    loan_id: 'LN-100215',
    canonical_data: loans[14],
    source_file_ref: 'tape_2026_08_encompass.csv',
    validation_result: 'pass',
    reviewer_decision: 'approved',
    ai_recommendation_ref: null,
    verified_at: t('2026-08-09', '11:27:00'),
    verified_by: 'Reviewer A',
    record_hash: '0x1a7d4c0f3e6b9d2a5c8f1e4b7a0d3c6f9e2b5a8d1c4f7e0b3a6d9c2f5e8b1a',
  },
  {
    loan_id: 'LN-100216',
    canonical_data: loans[15],
    source_file_ref: 'tape_2026_08_mortgagecadence.csv',
    validation_result: 'pass',
    reviewer_decision: 'approved',
    ai_recommendation_ref: null,
    verified_at: t('2026-08-08', '08:19:00'),
    verified_by: 'Reviewer B',
    record_hash: '0x6d9c2f5e8b1a4d7c0e3b6a9d2f5c8e1b4a7d0c3f6e9b2a5d8c1a7d4c0f3e6b',
  },
  {
    loan_id: 'LN-100217',
    canonical_data: loans[16],
    source_file_ref: 'tape_2026_08_encompass.csv',
    validation_result: 'pass',
    reviewer_decision: 'approved',
    ai_recommendation_ref: null,
    verified_at: t('2026-08-07', '15:02:00'),
    verified_by: 'Reviewer A',
    record_hash: '0x0f3e6b9d2a5c8f1e4b7a0d3c6f9e2b5a8d1c4f7e0b3a6d9c2f5e8b1a4d7c0e3b',
  },
  {
    loan_id: 'LN-100220',
    canonical_data: loans[19],
    source_file_ref: 'tape_2026_08_mortgagecadence.csv',
    validation_result: 'pass',
    reviewer_decision: 'approved',
    ai_recommendation_ref: null,
    verified_at: t('2026-08-06', '12:44:00'),
    verified_by: 'Reviewer B',
    record_hash: '0x9d2a5c8f1e4b7a0d3c6f9e2b5a8d1c4f7e0b3a6d9c2f5e8b1a4d7c0e3b6a3f',
  },
  {
    loan_id: 'LN-100221',
    canonical_data: loans[20],
    source_file_ref: 'tape_2026_08_encompass.csv',
    validation_result: 'pass',
    reviewer_decision: 'approved',
    ai_recommendation_ref: null,
    verified_at: t('2026-08-05', '09:11:00'),
    verified_by: 'Reviewer A',
    record_hash: '0x5c8f1e4b7a0d3c6f9e2b5a8d1c4f7e0b3a6d9c2f5e8b1a4d7c0e3b6a9d2a3f',
  },
  {
    loan_id: 'LN-100223',
    canonical_data: loans[22],
    source_file_ref: 'tape_2026_08_encompass.csv',
    validation_result: 'pass',
    reviewer_decision: 'approved',
    ai_recommendation_ref: null,
    verified_at: t('2026-08-04', '10:36:00'),
    verified_by: 'Reviewer A',
    record_hash: '0x4b7a0d3c6f9e2b5a8d1c4f7e0b3a6d9c2f5e8b1a4d7c0e3b6a9d2a5c8f1e3b',
  },
];

const auditFor = (loanId: string): AuditEvent[] => {
  const base: AuditEvent[] = [
    {
      event_type: 'uploaded',
      entity_type: 'loan',
      entity_id: loanId,
      actor: 'Data Operator',
      timestamp: t('2026-08-15', '07:30:00'),
      detail: 'File tape_2026_08_encompass.csv uploaded',
    },
    {
      event_type: 'imported',
      entity_type: 'loan',
      entity_id: loanId,
      actor: 'System',
      timestamp: t('2026-08-15', '07:30:12'),
      detail: 'Row parsed and imported',
    },
    {
      event_type: 'validated',
      entity_type: 'loan',
      entity_id: loanId,
      actor: 'Validation Engine',
      timestamp: t('2026-08-15', '07:30:20'),
      detail: 'Validation rules executed',
    },
  ];
  const ex = exceptions.filter((e) => e.loan_id === loanId);
  ex.forEach((e) => {
    base.push({
      event_type: 'exception_created',
      entity_type: 'exception',
      entity_id: e.id,
      actor: 'Validation Engine',
      timestamp: e.detected_at,
      detail: `${e.rule_type} — ${e.severity} severity`,
    });
    const rec = recommendations.find((r) => r.exception_id === e.id);
    if (rec) {
      base.push({
        event_type: 'ai_recommendation_generated',
        entity_type: 'recommendation',
        entity_id: rec.id,
        actor: rec.model,
        timestamp: rec.timestamp,
        detail: 'AI recommendation generated',
      });
    }
  });
  const v = verifiedRecords.find((r) => r.loan_id === loanId);
  if (v) {
    base.push({
      event_type: 'decision',
      entity_type: 'loan',
      entity_id: loanId,
      actor: v.verified_by,
      timestamp: t(v.verified_at.slice(11, 21), v.verified_at.slice(11, 19)),
      detail: `Loan ${v.reviewer_decision}`,
    });
    base.push({
      event_type: 'verified',
      entity_type: 'verified',
      entity_id: loanId,
      actor: v.verified_by,
      timestamp: v.verified_at,
      detail: `Record verified — hash ${v.record_hash.slice(0, 18)}…`,
    });
  }
  return base.sort((a, b) => a.timestamp.localeCompare(b.timestamp));
};

export const auditByLoan: Record<string, AuditEvent[]> = Object.fromEntries(
  loans.map((l) => [l.loan_id, auditFor(l.loan_id)]),
);

export const importEvents: ImportEvent[] = [
  {
    id: 'IMP-9001',
    file_name: 'tape_2026_08_encompass.csv',
    source_system: 'Encompass',
    uploaded_at: t('2026-08-15', '07:30:00'),
    rows_imported: 9,
    rows_failed: 1,
    rows_flagged: 4,
    status: 'parsed',
    failed_rows: [
      { row: 14, loan_id: null, reason: 'Missing origination_date — row skipped' },
    ],
  },
  {
    id: 'IMP-9002',
    file_name: 'tape_2026_08_byte.csv',
    source_system: 'Byte',
    uploaded_at: t('2026-08-15', '07:42:00'),
    rows_imported: 5,
    rows_failed: 0,
    rows_flagged: 2,
    status: 'parsed',
  },
  {
    id: 'IMP-9003',
    file_name: 'tape_2026_08_calyx.csv',
    source_system: 'Calyx Point',
    uploaded_at: t('2026-08-15', '08:01:00'),
    rows_imported: 3,
    rows_failed: 0,
    rows_flagged: 2,
    status: 'parsed',
  },
  {
    id: 'IMP-9004',
    file_name: 'tape_2026_08_mortgagecadence.csv',
    source_system: 'MortgageCadence',
    uploaded_at: t('2026-08-15', '08:15:00'),
    rows_imported: 3,
    rows_failed: 0,
    rows_flagged: 1,
    status: 'parsed',
  },
  {
    id: 'IMP-9005',
    file_name: 'tape_2026_08_lendingqb.csv',
    source_system: 'LendingQB',
    uploaded_at: t('2026-08-15', '08:30:00'),
    rows_imported: 2,
    rows_failed: 0,
    rows_flagged: 2,
    status: 'parsed',
  },
  {
    id: 'IMP-9006',
    file_name: 'tape_2026_07_legacy.csv',
    source_system: 'Encompass',
    uploaded_at: t('2026-07-28', '09:10:00'),
    rows_imported: 0,
    rows_failed: 12,
    rows_flagged: 0,
    status: 'failed',
    failed_rows: [
      { row: 1, loan_id: null, reason: 'Header row mismatch — expected 15 columns, found 11' },
    ],
  },
];

export const summary: Summary = {
  total_loans: loans.length,
  total_exceptions: exceptions.length,
  open_exceptions: exceptions.filter((e) => e.status === 'open').length,
  verified_records: verifiedRecords.length,
  pending_review: exceptions.filter((e) => e.status === 'open').length,
  pass_rate: Math.round(
    (verifiedRecords.length / loans.length) * 1000,
  ) / 10,
};

export const operatorDashboard: OperatorDashboard = {
  recent_imports: importEvents,
  validation: {
    pass: loans.length - exceptions.length,
    fail: importEvents.reduce((n, i) => n + i.rows_failed, 0),
    flagged: exceptions.length,
  },
  needs_correction: exceptions
    .filter((e) => e.status === 'open' || e.status === 'correction_requested')
    .map((e) => ({
      loan_id: e.loan_id,
      rule_type: e.rule_type,
      severity: e.severity,
    })),
};

export const reviewerDashboard: ReviewerDashboard = {
  by_severity: {
    high: exceptions.filter((e) => e.severity === 'high' && e.status === 'open').length,
    medium: exceptions.filter((e) => e.severity === 'medium' && e.status === 'open').length,
    low: exceptions.filter((e) => e.severity === 'low' && e.status === 'open').length,
  },
  pending_decisions: exceptions.filter((e) => e.status === 'open').length,
  recent_decisions: [
    {
      loan_id: 'LN-100201',
      decision: 'approved',
      actor: 'Reviewer A',
      at: t('2026-08-16', '08:51:00'),
    },
    {
      loan_id: 'LN-100202',
      decision: 'approved',
      actor: 'Reviewer B',
      at: t('2026-08-15', '13:22:00'),
    },
    {
      loan_id: 'LN-100205',
      decision: 'correction_requested',
      actor: 'Reviewer A',
      at: t('2026-08-17', '14:28:00'),
    },
  ],
  ai_summary:
    '8 open exceptions in the queue. 3 are high-severity documentation gaps (missing closing disclosures or HELOC agreements) — these should be held for correction, not auto-verified. 2 are low-severity pending documents that will clear once the missing paperwork is uploaded. 2 are days-past-due consistency checks that need servicer confirmation before a decision. The AI recommends working the high-severity items first.',
};

export const consumerDashboard: ConsumerDashboard = {
  verified_count: verifiedRecords.length,
  data_quality_score: 96.4,
  verification_history: verifiedRecords
    .map((v) => ({
      loan_id: v.loan_id,
      verified_at: v.verified_at,
      verified_by: v.verified_by,
    }))
    .sort((a, b) => b.verified_at.localeCompare(a.verified_at))
    .slice(0, 8),
};
